apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinyproxy-new
  namespace: shiny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shinyproxy-new
  template:
    metadata:
      labels:
        app: shinyproxy-new
    spec:
      containers:
      - name: shinyproxy
        image: 713007925222.dkr.ecr.eu-west-1.amazonaws.com/shinyproxy-application:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /srv/shiny-server/data  # This should be the root of your EFS
          name: efs-storage
      - name: kube-proxy-sidecar
        image: 713007925222.dkr.ecr.eu-west-1.amazonaws.com/kube-proxy-sidecar:v1
        ports:
        - containerPort: 8001
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-pvc

