apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shinyproxy-hpa
  namespace: shiny
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shinyproxy-new
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
