apiVersion: v1
kind: ServiceAccount
metadata:
  name: shinyproxy-restarter
  namespace: shiny
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shinyproxy-restarter-role
  namespace: shiny
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames: ["shinyproxy-new"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shinyproxy-restarter-binding
  namespace: shiny
subjects:
- kind: ServiceAccount
  name: shinyproxy-restarter
  namespace: shiny
roleRef:
  kind: Role
  name: shinyproxy-restarter-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: shinyproxy-restart
  namespace: shiny
spec:
  schedule: "0 */12 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 120
      backoffLimit: 2
      template:
        spec:
          serviceAccountName: shinyproxy-restarter
          restartPolicy: Never
          containers:
          - name: kubectl
            image: bitnami/kubectl:1.34
            command: ["kubectl", "rollout", "restart", "deployment/shinyproxy-new", "-n", "shiny"]
