apiVersion: v1
kind: Service
metadata:
  name: shinyproxy-service-new
  namespace: shiny
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
  selector:
    app: shinyproxy-new
  type: LoadBalancer

