
#Tidy up inverted commas so they are consistent

intro_tab<-tabPanel("Intro",icon=icon("door-open"),
                      value="intro",
                      titlePanel("Introduction"),
                      tags$a("For more detail see the Help page's Introduction section",
                           href="https://oasislmf.github.io/RiskExplorer/components/index_UserGuide.html",
                           target="_blank"),br(),
                    tags$a("Please see legal disclaimer before running",
                           href="https://oasislmf.github.io/RiskExplorer/components/index_Disclaimer.html",
                           target="_blank"),
                      column(9,helptextUI('intro')),
                      column(3,actionButton('i_nextpage', 'Go to Next Page')))

exposure_tab<-tabPanel("1.Exposure",icon=icon("building"),
         value="exposure",
         titlePanel("1.Exposure"),
         helptextUI('exposureinput'),
         tags$a("For more detail see the Help page's Exposure user guide",
                href="https://oasislmf.github.io/RiskExplorer/components/index_Walkthrough.html#exposure",
                target="_blank"),
         h4("Step 1: Choose Location to Model"),
         selectInput("e_ll_known", "Do you know the latitude and longitude co-ordinates of the location you are modelling?", 
                      c("Yes", "No"),selected="No"),
         conditionalPanel(condition="input.e_ll_known=='No'",
                         column(6,helpText("Drop a pin on the map by clicking on the relevant location. You may also look up
                         the address using the magnifying glass icon in the top left."))),
         conditionalPanel(condition="input.e_ll_known=='Yes'",
                          column(6,helpText("Enter lat-long co-ordinates manually to display on map. Note that these are entered 
                                            on a plus minus scale. E.g. -130 longitude is 130 degrees west and 45 latitude is 45
                                            degrees north."))),
         tags$script(HTML('$e_input_mapContainer.on(\'map-container-resize\', function () {
           e_input_map.invalidateSize();')),
         leafletOutput('e_input_map',height="50vh",width="50vw"),
         conditionalPanel(condition="input.e_ll_known=='Yes'",
                          column(6,numericInput("e_lat_input","Latitude (degrees)","",min = -90.00,max = 90.00,step=0.01)),
                          column(6,numericInput("e_lng_input","Longitude (degrees)","",min = -180.00,max = 180.00,step=0.01))),
         htmltools::span(uiOutput("e_input_error_message"),style="color:red;font-size:16px"),
         tableOutput('e_selected_ll_tbl'),
         h4("Step 2: Specify the size of the area around the chosen location that you wish to be covered."),
         helpText("This may be entered in km or miles. If you are only interested in a single location then just select 
                  zero here."),br(),
         radioButtons("e_shape_units","Select units",choices=c("km","miles"),selected="km"),
         numericInput("e_shape_p1","Radius in km or miles",value=""),
         htmltools::span(uiOutput("e_circle_warning"),style="color:red;font-size:16px"),
         h4("Step 3: Enter your Asset Value and Currency"),
         helpText("Enter an asset value greater than zero and select the appropriate currency."),
         fluidRow(
           column(4,autonumericInput("v_max_insured","Asset Value",value=0,digitGroupSeparator = ",",decimalPlaces = 0)),
           column(4,selectInput("v_curr","Currency",choices=curr_cd$Code,selected = "USD"))),
         htmltools::span(uiOutput("e_exposure_complete"),style="color:green;font-size:20px"),
         fluidRow(column(3,actionButton('e_prevpage', 'Go to Previous Page')),
                  column(3,actionButton('e_nextpage', 'Go to Next Page'))),
         br(),br())

hazard_tab<-tabPanel("2.Hazard",icon=icon("cloud-showers-heavy"),
                     value="hazard",
                     titlePanel("2.Hazard"),
                     helptextUI('hazard1'),
                     tags$a("For more detail see the Help page's Hazard user guide",
                            href="https://oasislmf.github.io/RiskExplorer/components/index_Walkthrough.html#exposure",
                            target="_blank"),
                     h4('Step 1: Choose your peril, region and selected data'),
                     helptextUI('hazard2'),
                     selectInput("h_peril",label='Peril',
                                  choices=unique(h_mappings$peril),selected=""),
                     selectInput("h_dataset",label='Data Source',
                                 choices=NULL,selected=""),
                     selectInput("h_region",label='Region',
                                 choices=NULL,selected=""),
                     htmltools::span(uiOutput("h_suggested_region"),style="color:red;font-size:16px"),
                     selectInput("h_agency",label='Meteorological Agency',
                                 choices=NULL,selected=""),
                     textOutput("h_agency_text"),
                     htmltools::span(uiOutput("h_hazard_complete"),style="color:green;font-size:16px"),
                     br(),
                     column(6,actionButton("h_data_load","Load Hazard Data")),
                     h4('Step 2 (optional): Visualise your hazard data'),
                     helpText('For IBTrACS, approximate historical storm tracks for the last 10 years of hazard data are available.
                     Exposure and the simulation sample area will display below based on the data you have loaded in step 1. For stochastic sets, 
                              the exposure and area that the model covers will be displayed. This step is not required to run the model.',
                              br(),br()),
                     column(6,actionButton("h_display_tracks","Display Hazard and Exposure")),
                     br(),
                     leafletOutput('h_map',height="50vh",width="50vw"),
                     br(),
                     fluidRow(column(3,actionButton('h_prevpage', 'Go to Previous Page')),
                              column(3,actionButton('h_nextpage', 'Go to Next Page'))),
                     br(),br())
                     
vulnerability_tab<-tabPanel("3.Vulnerability",icon=icon("ruler-vertical"),
         value="vulnerability",
         titlePanel("3.Vulnerability"),
         helptextUI('vulnerability1'),
         tags$a("For more detail see the Help page's Vulnerability user guide",
                href="https://oasislmf.github.io/RiskExplorer/components/index_Walkthrough.html#vulnerability",
                target="_blank"),
         h4("Step 1: Choose your trigger measure and response basis"),
         helpText(strong("Note that changing the intensity measure selection/unit will re-load the defaults and clear any edits 
                  you have already made to the table below")),
         fluidRow(column(4,selectInput("v_intensity","Intensity Measure Selection",choices=c("Wind Speed","Pressure","Peak Ground Acceleration"),selected="")),
         column(4,selectInput("v_intensity_unit","Intensity Measure Unit",choices=NULL,selected="km/h"))),
         htmltools::span(uiOutput("v_suggested_intensity"),style="color:red;font-size:16px"),
         h4("Step 2: Choose your vulnerability curve"),
         selectInput("v_curve_type","Select Curve Type",choices=c("Step","Linear"),selected="Step"),
         h4("Step 3: Enter your vulnerability function"),
         helptextUI('vulnerability2'),
         DTOutput("v_structure_DT"),
         htmltools::span(uiOutput("v_table_warning"),style="color:red;font-size:20px"),
         column(9,plotlyOutput("v_structure_plot")),
         htmltools::span(uiOutput("v_vulnerability_complete"),style="color:green;font-size:20px"),
         fluidRow(column(3,actionButton('v_prevpage', 'Go to Previous Page')),
                  column(3,actionButton('v_nextpage', 'Go to Next Page'))),
         br(),br())

simulation_tab<-tabPanel("4.Simulation",icon=icon("calculator"),
                         value="simulation",
                         titlePanel("4.Simulation"),
                         conditionalPanel(condition= "input.h_dataset=='IBTrACS Historical Data '",
                           helptextUI('sims')),
                         conditionalPanel(condition= "input.h_dataset!='IBTrACS Historical Data '",
                                          helptextUI('sims2')),
                         tags$a("For more detail see the Help page's Simulation user guide",
                                href="https://oasislmf.github.io/RiskExplorer/components/index_Walkthrough.html#simulation",
                                target="_blank"),
                         h4("Input Summary"),
                         htmlOutput("s_exposure_complete"),
                         htmlOutput("s_hazard_complete"),
                         htmlOutput("s_vulnerability_complete"),
                         h4("Choose how many simulations to run"),
                         selectInput("s_sims_n",label='Number of Sims to Run',
                                     choices=c(500,1000,2000,5000,10000),selected=500),
                         actionButton("s_simulation_run","Run Simulation"),
                         br(),br(),
                         fluidRow(column(3,actionButton('s_prevpage', 'Go to Previous Page')),
                                  column(3,actionButton('s_nextpage', 'Go to Next Page'))),
                         br(),br())

analysis_tab<-tabPanel("5.Events",icon=icon("poll"),
                       value="analysis",
                     titlePanel("5.Event Analysis"),
                     conditionalPanel(
                      condition = "!input.s_simulation_run",
                      h4("Exhibits will display here once simulations have been run in the Simulation tab")),
                     conditionalPanel("input.s_simulation_run",
                     helptextUI('analysis_summary'),
                     tags$a("For more detail see the Help page's Event Analysis user guide",
                            href="https://oasislmf.github.io/RiskExplorer/components/index_Walkthrough.html#analysis",
                            target="_blank"),
                       h4("Exhibit 1: Historical Loss Summary:"),
                     conditionalPanel(condition= "output.s_sim_ok_ibtracs == 'TRUE'",
                         helptextUI("analysis_ex1"),
                         tableOutput("a_ex1_summary"),
                         leafletOutput("a_historical_loss_map",height="50vh",width="50vw"),
                         dataTableOutput("a_ex1_DT")),
                     conditionalPanel(condition= "output.s_sim_ok_ibtracs == 'FALSE'",
                         helpText("There is no historical data available for stochastic sets. To
                         see a summary of historical events, re-run with IBTrACS data")),
                         h4("Exhibit 2: Individual Simulation Summary"),
                     conditionalPanel(condition= "output.s_sim_ok_ibtracs == 'TRUE'",
                         helptextUI("analysis_ex2")),
                     conditionalPanel(condition= "output.s_sim_ok_ibtracs == 'FALSE'",
                                      helptextUI("analysis_ex2_2")),
                         numericInput("a_ex2_sim_no","Select Sim No to Display on Map",
                                      value=1,min=1,max=10000),
                         tableOutput("a_ex2_summary"),
                         leafletOutput("a_ex2_map",height="50vh",width="50vw"),
                         dataTableOutput("a_ex2_DT"),
                         h4("Exhibit 3: Event Frequency and Return Periods"),
                         helptextUI("analysis_ex3"),
                         tableOutput("a_intensity_stats_table")),
                         fluidRow(column(3,actionButton('a_prevpage', 'Go to Previous Page')),
                              column(3,actionButton('a_nextpage', 'Go to Next Page'))),
                         br(),br())
                         


results_tab<-tabPanel("6.Losses",icon=icon("bullseye"),
                      value="results",
                      titlePanel("6.Losses"),
                      conditionalPanel(
                        condition = "!input.s_simulation_run",
                        h4("Results will display here once simulations have been run in the Simulation tab"),
                        ),
                      conditionalPanel(
                        condition = "input.s_simulation_run",
                        helptextUI('results_summary'),
                        tags$a("For more detail see the Help page's Loss Analysis user guide",
                               href="https://oasislmf.github.io/RiskExplorer/components/index_Walkthrough.html#results-summary",
                               target="_blank"),
                        h4("Display Options"),
                        selectInput("r_output_display",
                                    label="Display output as currency or percentage of asset value?",
                                    choices=c("Currency","% of Asset Value"),
                                    selected="Currency"
                        ),
                        h4("Exhibit 4: Payout Frequency Summary"),
                        helptextUI("analysis_ex4"),
                        column(12,plotlyOutput("a_loss_freq_chart")),
                        dataTableOutput("a_loss_freq_DT"),
                        h4("Exhibit 5: Expected Loss and Distribution by Calculation Method"),
                        helptextUI("results_1"),
                        column(10,plotlyOutput("r_graph_by_drop_dist")),
                        tableOutput("r_el_table"),
                        conditionalPanel(condition= "output.s_sim_ok_ibtracs == 'TRUE'",
                        helptextUI("results_2"),
                        h4(("Export Results to Excel")),
                        helptextUI('results_3')),
                        conditionalPanel(condition= "output.s_sim_ok_ibtracs == 'FALSE'",
                                         helptextUI("results_2_2"),
                                         h4(("Export Results to Excel")),
                                         helptextUI('results_3_2')),
                        downloadButton("r_downloadCircleDropData",label="Download output for each simulation"),
                        conditionalPanel(condition= "output.s_sim_ok_ibtracs == 'TRUE'",
                        br(),
                        downloadButton("r_downloadDataYearData",label="Download output for each simulation and data-year")),
                        ),
                      br(),
                      column(3,actionButton('r_prevpage', 'Go to Previous Page')),
                      br(),br())