
payout_text <-
  helpText(
    strong(
      "The Loss Analysis tab displays outputs once hazard, exposure and vulnerability 
      have been completed and simulations have been run.","The tab's purpose is to 
      give you an idea of the range of losses generated by the model and how much loss 
      to expect in an average year."
    )
  )
 
tab_payouts_UI <- function(id) {
  ns <- NS(id)
    tagList(
      shiny::titlePanel("6.Losses"),
      conditionalPanel(condition = "output.sim_run_success",
                       ns = ns,
                       payout_text,
                       br(),
                       l_payout_freq_UI(ns('payout_freq1')),
                       l_payout_summary_UI(ns('payout_summary1')),
                       l_download_payout_data_UI(ns('payout_download1'))
      ),
      page_nav_UI(ns("losses"))
    )
}

tab_payouts_Server <- function(id, parent, sim_output, display_type) {
  moduleServer(
    id,
    function(input, output, session) {
      
      output$sim_run_success <-
        reactive({
          FALSE
          req(sim_output())
          TRUE
        })
      
      outputOptions(output, "sim_run_success", suspendWhenHidden = FALSE)  
      
      observe({
        
        req(sim_output(), display_type())
        
        display_var <- assign_display_var(display_type())
        
        display_fun <- 
          return_display_format(display_type(),
                                peril = sim_output()$peril,
                                curr = sim_output()$curr,
                                sim_output()$expo_value)
        
        l_payout_freq_Server('payout_freq1',
                             sim_output = sim_output,
                             display_var = display_var, 
                             display_fun = display_fun)
        
        l_payout_summary_Server('payout_summary1',
                          sim_output = sim_output,
                          display_var = display_var, 
                          display_fun = display_fun)
        
        l_download_payout_data_Server('payout_download1',
                                      sim_output = sim_output)
      
      })
      
      page_nav_Server("losses",
                      parent = parent,
                      prev_page  = "events", 
                      next_page = NULL)
    }
  )
}
